language: python
python:
  - 3.5
services:
  - docker
install:
  - docker build -t mash:2.2 mash/2.2
  - docker build -t mashtree:1.2.0 mashtree/1.2.0
  - docker build -t spades:3.14.1 spades/3.14.1
  - docker build -t quast:5.0.2 quast/5.0.2
  - docker build -t shovill:1.1.0 shovill/1.1.0
  - docker build -t samtools:1.11 samtools/1.11
  - docker build -t abricate:1.0.0 abricate/1.0.0
  - docker build -t ariba:2.14.4 ariba/2.14.4
  - docker build -t ivar:1.2.2_artic20200528 ivar/1.2.2_artic20200528
script:
  - bash tests/mash-test.sh
  - bash tests/mashtree-test.sh
  - bash tests/spades.sh
  - bash tests/quast.sh
  - bash tests/shovill.sh
  - bash tests/samtools.sh
  - bash tests/abricate.sh
  - bash tests/ariba.sh
  - bash tests/ivar.sh
