##### --------------------------------------------------------------------------------------------------------- #####
##### This caller workflow tests, builds, and pushes the image to Docker Hub.                                   #####
##### It also tests that a Singularity container can be run from the Docker image.                              #####
##### Instructions: replace all the <placeholder> stubs in this template with values for your image.            #####
##### Some explanations come from: https://github.com/actions/starter-workflows/blob/main/automation/manual.yml #####
##### --------------------------------------------------------------------------------------------------------- #####

name: Deploy smalt image

# This workflow should run when manually triggered by StaPH-B repo maintainer
on: workflow_dispatch

# set variables for docker container
env:
  TOOL_NAME: smalt
  TOOL_VERSION: 0.7.9

##### ------------------------------------------------------- #####
##### Does not need to be edited below this line              #####
##### This calls the jobs for                                 #####
##### 1) testing the dockerfile (again)                       #####
##### 2) deploying the docker container to quay and dockerhub #####
##### 3) testing with singularity                             #####
##### ------------------------------------------------------- #####
jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - id: env-vars
        run: echo "::set-output name=params::$(echo $(jq -n 'env'))"

  build-to-test:
    needs: [params]
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./${{ fromJson(needs.params.outputs.params).TOOL_NAME }}/${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}"
      dockerfile_name: "Dockerfile"
      cache: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}"

  build-to-deploy:
    needs: [params, build-to-test]
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      quay_username: ${{ secrets.quay_username }}
      quay_robot_token: ${{ secrets.quay_robot_token }}
    with:
      path_to_context: "./${{ fromJson(needs.params.outputs.params).TOOL_NAME }}/${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}"
      dockerfile_name: "Dockerfile"
      cache: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}"
      container_name: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}"
      tag: ${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}

  build-to-run-singularity:
    needs: [params, build-to-deploy]  # test singularity run on newly pushed Docker image
    uses: StaPH-B/docker-builds/.github/workflows/build-to-run-singularity.yml@master
    with:
      image_name: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}:${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}"
