name: Test blast+ image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'blast/*/Dockerfile'

jobs:
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "blast/2.13.0"
      dockerfile_name: "Dockerfile"
      cache: "blast"
