name: Test MaSuRCA image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "masurca/4.0.8/Dockerfile"

jobs:
  build-to-test:
    uses: .StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./masurca/4.0.8"
      dockerfile_name: "Dockerfile"
      cache: "masurca"
