name: Test bowtie2 image
on:
 workflow_dispatch:
 pull_request:
 paths:
 - 'bowtie2/*/Dockerfile'
jobs:
 build-to-test:
 uses: ./.github/workflows/build-to-test.yml
 with:
 path_to_context: "bowtie2/2.4.5"
 dockerfile_name: "Dockerfile"
 cache: "bowtie2"
