name: Test htslib image

env:
  tool: "htslib"
  version: "1.15"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'htslib/1.15/Dockerfile'

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - id: env-vars
        run: echo "::set-output name=params::$(echo $(jq -n 'env'))"

  build-to-test:
    needs: [params]
    uses: ./.github/workflows/build-to-test.yml
    with:
      tool: "${{ fromJson(needs.params.outputs.params).tool }}"
      version: "${{ fromJson(needs.params.outputs.params).version }}"
